# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZiuJK9KMybN77AsqmaEmMNSLNv8LGWc
"""

"""Importing the Dependencies"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# loading the dataset into a Pandas DataFrame
credit_card_data = pd.read_csv("creditcard.csv")

# first 5 rows of the dataset
credit_card_data.head()

# last 5 rows of the dataset
credit_card_data.tail()

# dataset information
credit_card_data.info()

# checking the number of missing values in each column
credit_card_data.isnull().sum()

# distribution of legitimate transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

"""
This Dataset is highly imbalanced

0 --> Normal Transaction
1 --> Fraudulent Transaction
"""

# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

print("Legitimate transactions shape:", legit.shape)
print("Fraudulent transactions shape:", fraud.shape)

# statistical measures of the 'Amount' for legitimate transactions
print("Legit Amount Description:")
print(legit.Amount.describe())

# statistical measures of the 'Amount' for fraudulent transactions
print("Fraud Amount Description:")
print(fraud.Amount.describe())

# comparing the mean values for both transaction types
print("Grouped Means:")
print(credit_card_data.groupby('Class').mean())

"""Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and fraudulent transactions.

Number of Fraudulent Transactions --> 500 (approximately)
"""

# Under-sampling the legitimate transactions to balance the dataset
legit_sample = legit.sample(n=423)

"""Concatenating two DataFrames"""

# Creating a new dataset by combining the under-sampled legitimate transactions with all fraudulent transactions
new_dataset = pd.concat([legit_sample, fraud], axis=0)

print("New dataset head:")
print(new_dataset.head())

print("New dataset tail:")
print(new_dataset.tail())

print("New dataset Class distribution:")
print(new_dataset['Class'].value_counts())

print("Grouped means for new dataset:")
print(new_dataset.groupby('Class').mean())

"""Splitting the data into Features & Targets"""

X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

print("Features (X):")
print(X.head())
print("Target (Y):")
print(Y.head())

"""Split the data into Training Data & Testing Data"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
print("Overall shape:", X.shape)
print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

"""Model Training - Logistic Regression"""

model = LogisticRegression()

# Training the Logistic Regression model with the Training Data
model.fit(X_train, Y_train)

"""Model Evaluation - Accuracy Score"""

# Accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print('Accuracy on Training Data:', training_data_accuracy)

# Accuracy on testing data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print('Accuracy on Testing Data:', test_data_accuracy)

"""Step 2: Save the Trained Model"""

import joblib

# Save the trained Logistic Regression model to disk as 'logistic_model.pkl'
joblib.dump(model, 'logistic_model.pkl')
print("Trained model saved as 'logistic_model.pkl'.")
